name: Build, Lint, Test and Deploy

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  schedule:
    - cron: '0 0 * * 1'  # Weekly security scan

permissions:
  contents: read
  security-events: write
  pull-requests: write

jobs:
  build-lint-test:
    needs: version-bump
    if: always()
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    permissions:
      contents: read
      security-events: write
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node:
          - 20

    outputs:
      vsixPath: ${{ steps.packageExtension.outputs.vsixPath }}

    steps:
      - name: Setup GIT for Windows
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
        if: runner.os == 'Windows'

      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better versioning

      - name: Install Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'  # Enable yarn caching

      - name: Install Dependencies
        run: yarn install --immutable
        
      - name: Run yarn audit
        run: yarn npm audit --environment production
        continue-on-error: true  # Don't fail the build, but report issues
        
      - name: Run Linter
        run: yarn run eslint

      - name: Build Code (Standard)
        run: yarn run compile
        if: github.event_name != 'release'

      - name: Build Code (Release)
        run: yarn run package
        if: github.event_name == 'release'

      - name: Run Unit Tests on Windows or macOS
        run: yarn run test
        if: runner.os != 'Linux'

      - name: Run Unit Tests on Linux
        run: xvfb-run -a yarn run test
        if: runner.os == 'Linux'

      - name: Package Extension
        id: packageExtension
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: stub
          dryRun: true

      - name: Upload Extension Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: ${{ steps.packageExtension.outputs.vsixPath }}
          retention-days: 5  # Limit artifact retention
  
  version-bump:
    name: Version Bump
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write
      security-events: write
    strategy:
      fail-fast: true

    steps:
      - name: Checkout Source
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.YOUR_GITHUB_APP_ID }}
          private-key: ${{ secrets.YOUR_GITHUB_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0  # Full history for better versioning
          ref: "main"
      
      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable
      
      - name: Validate CHANGELOG
        run: |
          # Extract version from release tag (e.g. v1.2.3 -> 1.2.3)
          VERSION=${GITHUB_REF#refs/tags/v}
          
          # Check if version exists in CHANGELOG.md
          if ! grep -q "## \[${VERSION}\]" CHANGELOG.md; then
            echo "Error: Version ${VERSION} not found in CHANGELOG.md"
            echo "Please update CHANGELOG.md with the latest version before creating a release"
            exit 1
          fi
          
          echo "✓ CHANGELOG.md contains version ${VERSION}"
        
      - name: Update Version
        id: increment-version
        run: |
          # Extract version from release tag (e.g. v1.2.3 -> 1.2.3)
          VERSION=${GITHUB_REF#refs/tags/v}
          
          # Update package.json version
          yarn version $VERSION
          
          # Set VERSION as an output variable
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: "github_actions"
          message: "Increment version to ${{ steps.increment-version.outputs.VERSION }} [skip ci]"
          add: "*.json"
          tag: "${{ github.ref_name }} --force"
        
  publish:
    name: Publish Github Action
    needs:
      - version-bump
      - build-lint-test
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
      packages: write
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for better versioning
      
      - name: Install Node v20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --immutable
        
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ubuntu-latest
          
      - name: Verify Artifact Checksum
        run: |
          echo "Verifying artifact integrity..."
          sha256sum ${{ needs.build-lint-test.outputs.vsixPath }}
         
      - name: Publish to Visual Studio Marketplace
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          extensionFile: ${{ needs.build-lint-test.outputs.vsixPath }}
          registryUrl: https://marketplace.visualstudio.com
          
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        id: publishToOpenVSX
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
          extensionFile: ${{ needs.build-lint-test.outputs.vsixPath }}

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: false
          name: ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: ${{ needs.build-lint-test.outputs.vsixPath }}

  cleanup-on-failure:
    name: Cleanup Failed Release
    needs: publish
    if: failure() && github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete Failed Release Tag
        run: |
          echo "Cleaning up failed release..."
          
          # Delete the local tag
          git tag -d ${GITHUB_REF#refs/tags/}
          
          # Delete the remote tag
          git push --delete origin ${GITHUB_REF#refs/tags/}
          
          echo "✓ Cleaned up release tag ${GITHUB_REF#refs/tags/}"
